### ISSUE TITLE
Error on app start.

### ISSUE THREAD

**Issue by sheikhhaziq** [ubuntu/yaru.dart#994]
ERROR: ../../.pub-cache/hosted/pub.dev/yaru-7.0.0/lib/src/themes/common_themes.dart:738:18: Error: The argument type 'TabBarTheme' can't be assigned to the parameter type 'TabBarThemeData?'.

**Comment by Feichtmeier** [comment]
> ERROR: ../../.pub-cache/hosted/pub.dev/yaru-7.0.0/lib/src/themes/common_themes.dart:738:18: Error: The argument type 'TabBarTheme' can't be assigned to the parameter type 'TabBarThemeData?'.

we didnt make a new release for flutter 3.32.0 yet. you could use it from ref until then in pubspec

**Comment by EchoEllet** [comment]
This issue has been fixed in https://github.com/ubuntu/yaru.dart/pull/992 but not yet published (see https://github.com/ubuntu/yaru.dart/pull/976).

**Temporary solution** to use `yaru` with Flutter 3.32:

```yaml
dependency_overrides:
  # Remove the override if this PR is merged: https://github.com/ubuntu/yaru.dart/pull/976
  yaru:
    git:
      url: https://github.com/ubuntu/yaru.dart.git
      ref: release-please--branches--main--components--yaru
```
